name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
      
      - name: Create basic documentation structure
        run: |
          mkdir -p docs/source
          
          # Create a minimal conf.py
          echo 'project = "VERUS"' > docs/source/conf.py
          echo 'copyright = "2025, VERUS Team"' >> docs/source/conf.py
          echo 'author = "VERUS Team"' >> docs/source/conf.py
          echo 'extensions = ["sphinx.ext.autodoc"]' >> docs/source/conf.py
          echo 'html_theme = "sphinx_rtd_theme"' >> docs/source/conf.py
          
          # Create a minimal index.rst
          echo 'VERUS Documentation' > docs/source/index.rst
          echo '===================' >> docs/source/index.rst
          echo '' >> docs/source/index.rst
          echo 'Welcome to VERUS documentation.' >> docs/source/index.rst
          
      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html source build/html
      
      - name: Archive documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/build/html
