name: Build and Deploy Documentation

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Required for GitHub Pages deployment

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  # Install all documentation dependencies explicitly
                  pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints nbsphinx

                  # If you have a requirements file, also install it
                  if [ -f requirements.txt ]; then
                    pip install -r requirements.txt
                  fi

                  # Display installed packages for debugging
                  pip freeze

            - name: Create documentation structure
              run: |
                  mkdir -p docs/source

                  # Create minimal conf.py if it doesn't exist
                  if [ ! -f docs/source/conf.py ]; then
                    echo 'project = "VERUS"' > docs/source/conf.py
                    echo 'copyright = "2025, VERUS Team"' >> docs/source/conf.py
                    echo 'author = "VERUS Team"' >> docs/source/conf.py
                    echo 'extensions = ["sphinx.ext.autodoc", "sphinx.ext.viewcode", "sphinx_rtd_theme"]' >> docs/source/conf.py
                    echo 'html_theme = "sphinx_rtd_theme"' >> docs/source/conf.py
                  else
                    # Modify existing conf.py to remove problematic extension
                    sed -i '/sphinx_autodoc_typehints/d' docs/source/conf.py
                  fi

                  # Create minimal index.rst if it doesn't exist
                  if [ ! -f docs/source/index.rst ]; then
                    echo 'VERUS Documentation' > docs/source/index.rst
                    echo '===================' >> docs/source/index.rst
                    echo '' >> docs/source/index.rst
                    echo 'Welcome to VERUS documentation.' >> docs/source/index.rst
                  fi

            - name: Debug documentation files
              run: |
                  echo "Contents of docs directory:"
                  ls -la docs/
                  echo "Contents of docs/source directory:"
                  ls -la docs/source/
                  echo "Content of conf.py:"
                  cat docs/source/conf.py

            - name: Build documentation
              run: |
                  cd docs
                  sphinx-build -b html source build/html

            - name: Archive documentation
              uses: actions/upload-artifact@v4
              with:
                  name: documentation
                  path: docs/build/html

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: docs/build/html
